# 4 node (3 workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.28.0
    extraMounts:
      - hostPath: "./profiles"
        containerPath: "/var/lib/kubelet/seccomp/profiles"

